"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveAppBar from "@/components/mui/appBar/appbar";
import { ProductOrderContextProvider } from "@/context/productContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductOrderContextProvider>
          <ResponsiveAppBar
            logo="MY LOGO"
            pages={[
              { label: "Home", href: "/" },
              { label: "About", href: "/about" },
              { label: "Orders", href: "/order" },
              { label: "Products", href: "/product" },
            ]}
            settings={["Profile", "Logout"]}
            avatarSrc="https://robohash.org/7b4fecbc8b873e2e3329baf33208c9f6?set=set4&bgset=bg1&size=200x200"
          />
          {children}
        </ProductOrderContextProvider>
      </body>
    </html>
  );
}
